export const GET_ADMIN_BRANDS_SEARCH_MAX_LENGTH = 100
export const GET_ADMIN_BRANDS_MAX_LIMIT = 100
export const GET_ADMIN_BRANDS_CURSOR_MAX_LENGTH = 100

export const ADMIN_BRAND_NAME_MAX_LENGTH = 30
