export const GET_PRODUCT_SKUS_SEARCH_MAX_LENGTH = 100
export const GET_PRODUCT_SKUS_MAX_LIMIT = 50
export const GET_PRODUCT_SKUS_DEFAULT_LIMIT = 30
export const GET_PRODUCT_SKUS_CURSOR_MAX_LENGTH = 100
