export const GET_ADMIN_CATEGORIES_SEARCH_MAX_LENGTH = 100
export const GET_ADMIN_CATEGORIES_MAX_LIMIT = 100
export const GET_ADMIN_CATEGORIES_CURSOR_MAX_LENGTH = 100

export const ADMIN_CATEGORY_NAME_MAX_LENGTH = 30
