export const GET_ADMIN_PRODUCTS_SEARCH_MAX_LENGTH = 100
export const GET_ADMIN_PRODUCTS_MAX_LIMIT = 100
export const GET_ADMIN_PRODUCTS_CURSOR_MAX_LENGTH = 100

export const ADMIN_PRODUCT_TITLE_MAX_LENGTH = 60
export const ADMIN_PRODUCT_DESCRIPTION_MAX_LENGTH = 200
export const ADMIN_PRODUCT_TAGS_MAX_LENGTH = 20
